version: '3.4'

services:
  usersdb:
    container_name: usersdb
    restart: always
    ports: 
        - "27017:27017"
    volumes:
        - mongo_data:/data/db

  users.api:
    container_name: users.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DBSettings:ConnectionString=mongodb://usersdb:27017"
    depends_on:
        - usersdb
    ports:
      - "8000:80"
